class _BotCommands:
    def __init__(self):
        self.LeechCommand = 'leech'
        self.gLeechCommand = 'gleech'
        self.ExtractCommand = 'extract'
        self.gExtractCommand = 'gextract'
        self.ArchiveCommand = 'archive'
        self.gArchiveCommand = 'garchive'
        self.telegramfleechCommand = 'tleech'
        self.telegramexleechCommand = 'tleechextract'
        self.gcloneCommand = 'gclonex'
        self.YtdlCommand = 'ytdlx'
        self.gYtdlCommand = 'gytdlx'
        self.PytdlCommand = 'pytdlx'
        self.gPytdlCommand = 'pytdlx'        
        self.ToggleDocCommand = 'toggledocx'
        self.ToggleVidCommand = 'togglevidx'
        self.SaveCommand = 'savethumbx'
        self.ClearCommand = 'clearthumbx'
        self.RenameCommand = 'renamex'
        self.StatusCommand = 'statusx'
        self.SpeedCommand = 'speedtestx'
        self.HelpCommand = 'helpx'
        self.LogCommand = 'logx'
        self.TsHelpCommand = 'tshelpx'

BotCommands = _BotCommands()
