class _BotCommands:
    def __init__(self):
        self.LeechCommand = 'leechx'
        self.gLeechCommand = 'gleechx'
        self.ExtractCommand = 'extractx'
        self.gExtractCommand = 'gextractx'
        self.ArchiveCommand = 'archivex'
        self.gArchiveCommand = 'garchivex'
        self.telegramfleechCommand = 'tleechx'
        self.telegramexleechCommand = 'tleechextractx'
        self.gcloneCommand = 'gclonex'
        self.YtdlCommand = 'ytdlx'
        self.gYtdlCommand = 'gytdlx'
        self.PytdlCommand = 'pytdlx'
        self.gPytdlCommand = 'pytdlx'        
        self.ToggleDocCommand = 'toggledocx'
        self.ToggleVidCommand = 'togglevidx'
        self.SaveCommand = 'savethumbx'
        self.ClearCommand = 'clearthumbx'
        self.RenameCommand = 'renamex'
        self.StatusCommand = 'statusx'
        self.SpeedCommand = 'speedtestx'
        self.HelpCommand = 'helpx'
        self.LogCommand = 'logx'
        self.TsHelpCommand = 'tshelpx'

BotCommands = _BotCommands()
